#!/bin/bash

FROM=~/.vasy

if [[ ! -e $FROM ]]; then
    touch $FROM
fi

if [[ $# == 0 ]]; then
    echo -e "usage: $0 [-k|--keys] <key>\n"
    cat $FROM
    exit 1
fi


function show_keys {
    sed -e "s/^\(.*\):\(.*\)/\1/g" -- $FROM | tr -s "\n" " "
}

function get_path {
    KEY=$1
    VALUE=$(grep "^$QUERY: " -- $FROM | sed -e "s/^$QUERY: //g")
    if [[ -z "$VALUE" ]]; then
        echo "no path found for $QUERY"
        exit 2
    else
        echo $VALUE
        exit 0
    fi
}


QUERY=''
KEYS=0
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -k|--keys)
            KEYS=1
            shift
            ;;
        *)
            QUERY=$key
            ;;
    esac
    shift
done

if [[ $KEYS == 1 ]]; then
    show_keys
    exit 0
fi

GOTO=$(get_path "$QUERY")
if [[ $? = 0 ]]; then
    GOTO="${GOTO/#\~/$HOME}"
    echo $(eval "echo $GOTO")
    exit 0
else
    echo $GOTO
    exit 1
fi
